using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;

namespace StudentAlumniTrackingTool.WebPages
{
    public partial class SearchResults : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            // Make sure our query has content, if it does not, we don't search for anything
            int count = 0;
            string queryString = Request.ServerVariables["SearchQuery"];    // session var from Search
            if (queryString == null)
            {
                NoResultsPanel.Visible = true;
                ResultsPanel.Visible = false;
            }
            else
            {
                
                ResultsPanel.Visible = true;
                SqlDataSource1.ConnectionString = null;
                
            }
            // Take the query string as a session var "passed in" from Search and run it
            // First gather connection string
            string connectionString = ConfigurationManager.ConnectionStrings["ApplicationServices"].ConnectionString;
            SqlCommand sqlCom = new SqlCommand(queryString);
            SqlConnection sqlConn = new SqlConnection(connectionString);

            // Try running the command
            
            try {
                sqlCom = new SqlCommand("SELECT ");
                // The variables in the DataGrid NEED to be identical to what is in the SQL query
                sqlConn = new SqlConnection(connectionString);
                sqlConn.Open();

                /*
                 * Bind the datasource of the GridView on this SearchResults.aspx page to the
                 * results generated by running this query.
                 */

                // Execute SQL
                ResultsGridView.DataSource = sqlCom.ExecuteReader();

                // Bind
                ResultsGridView.DataBind();
            }
            
            catch (Exception ex) {
                Response.Redirect("Error.aspx");
                Session["ErrorOccured"] = ex.ToString();
            }
            finally {
                // Close and dispose (hey, that rhymed!)
                sqlConn.Close();
                sqlCom.Dispose();
            }
        }

        protected void ResultsGridView_SelectedIndexChanged(object sender, EventArgs e)
        {

        }
    }
}